export const RESTAURANT_DUMMY_DATA = [
  {
    id: 'rest-001',
    name: 'Sun valley restaurant',
    representative: null,
    phone: '08000000001',
    business_license: 'BL123',
    owner_nid: 'NID123',
    established_date: '2020-01-01',
    working_period: '9am - 9pm',
    large_option: 'Yes',
    location: 'Aueduase',
    restaurant_image: null,
    restaurant_image_url: 'assets/images/restaurant-picture.jpeg',
    rating: 4.8,
    status: 'Open',
    categories: [],
    foods: [],
    reviews: [],
    riders: [],
    estimated_delivery_time: '15–20 min',
    discount_percentage: 10,
    isFavorited: false,
  },
  {
    id: 'rest-002',
    name: 'Moon valley restaurant',
    representative: null,
    phone: '08000000002',
    business_license: 'BL124',
    owner_nid: 'NID124',
    established_date: '2020-02-01',
    working_period: '9am - 9pm',
    large_option: 'Yes',
    location: 'Aueduase',
    restaurant_image: null,
    restaurant_image_url: 'assets/images/restaurant-picture.jpeg',
    rating: 4.8,
    status: 'Open',
    categories: [],
    foods: [],
    reviews: [],
    riders: [],
    estimated_delivery_time: '15–20 min',
    discount_percentage: 15,
    isFavorited: false,
  },
  {
    id: 'rest-003',
    name: 'Sun valley restaurant',
    representative: null,
    phone: '08000000003',
    business_license: 'BL125',
    owner_nid: 'NID125',
    established_date: '2020-03-01',
    working_period: '9am - 9pm',
    large_option: 'Yes',
    location: 'Aueduase',
    restaurant_image: null,
    restaurant_image_url: 'assets/images/restaurant-picture.jpeg',
    rating: 4.8,
    status: 'Open',
    categories: [],
    foods: [],
    reviews: [],
    riders: [],
    estimated_delivery_time: '15–20 min',
    discount_percentage: 10,
    isFavorited: false,
  },
  {
    id: 'rest-004',
    name: 'Moon valley restaurant',
    representative: null,
    phone: '08000000004',
    business_license: 'BL126',
    owner_nid: 'NID126',
    established_date: '2020-04-01',
    working_period: '9am - 9pm',
    large_option: 'Yes',
    location: 'Aueduase',
    restaurant_image: null,
    restaurant_image_url: 'assets/images/restaurant-picture.jpeg',
    rating: 4.8,
    status: 'Open',
    categories: [],
    foods: [],
    reviews: [],
    riders: [],
    estimated_delivery_time: '15–20 min',
    discount_percentage: 15,
    isFavorited: false,
  },
  {
    id: 'rest-005',
    name: 'Sun valley restaurant',
    representative: null,
    phone: '08000000005',
    business_license: 'BL127',
    owner_nid: 'NID127',
    established_date: '2020-05-01',
    working_period: '9am - 9pm',
    large_option: 'Yes',
    location: 'Aueduase',
    restaurant_image: null,
    restaurant_image_url: 'assets/images/restaurant-picture.jpeg',
    rating: 4.8,
    status: 'Open',
    categories: [],
    foods: [],
    reviews: [],
    riders: [],
    estimated_delivery_time: '15–20 min',
    discount_percentage: 10,
    isFavorited: false,
  },
  {
    id: 'rest-006',
    name: 'Sun valley restaurant',
    representative: null,
    phone: '08000000006',
    business_license: 'BL128',
    owner_nid: 'NID128',
    established_date: '2020-06-01',
    working_period: '9am - 9pm',
    large_option: 'Yes',
    location: 'Aueduase',
    restaurant_image: null,
    restaurant_image_url: 'assets/images/restaurant-picture.jpeg',
    rating: 4.8,
    status: 'Open',
    categories: [],
    foods: [],
    reviews: [],
    riders: [],
    estimated_delivery_time: '15–20 min',
    discount_percentage: 10,
    isFavorited: false,
  },
];
